krateo-frontend:
  env:
    BFF_API_BASE_URL: http://localhost:8081
    AUTHN_API_BASE_URL: http://localhost:8082

krateo-bff:
  env:
    KRATEO_BFF_DEBUG: "true"
    KRATEO_BFF_CORS: "true"

krateo-gateway:
  env:
    KRATEO_GATEWAY_DEBUG: "true"
    KRATEO_GATEWAY_CACRT: "/tmp/ca.crt"
    KRATEO_GATEWAY_DNS_NAMES: "localhost"
    KRATEO_GATEWAY_IP_ADDRESSES: "127.0.0.1"
    KRATEO_BFF_SERVER: "http://krateo-bff.krateo-system.svc:8080"

authn-service:
  env:
    AUTHN_DEBUG: "true"
    AUTHN_KUBECONFIG_CLUSTER_NAME: "krateo"
    AUTHN_KUBECONFIG_CRT_EXPIRES_IN: "24h"
    AUTHN_KUBERNETES_URL: "https://kube-apiserver:6443"
    AUTHN_KUBECONFIG_PROXY_URL: "https://krateo-gateway.krateo-system.svc:8443"
    AUTHN_KUBECONFIG_CACRT: "/tmp/ca.crt"
    AUTHN_CORS: "true"
